#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = 

INC = 
CFLAGS = -Wall -std=c++11 -Wno-write-strings
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g `wx-config --debug=yes --version=3.0 --cxxflags`
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) 
LDFLAGS_DEBUG = $(LDFLAGS) `wx-config --debug=yes --version=3.0 --libs base,core,adv,net`
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/wxRemoteTShockManager

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) `wx-config --debug=no --version=3.0 --cxxflags`
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -s `wx-config --debug=no --version=3.0 --libs base,core,adv,net`
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/wxRemoteTShockManager

OBJ_DEBUG = $(OBJDIR_DEBUG)/MyApp.o $(OBJDIR_DEBUG)/IHM/MainFrame.o $(OBJDIR_DEBUG)/IHM/UserModDialog.o $(OBJDIR_DEBUG)/src/RESTClient.o $(OBJDIR_DEBUG)/src/checktreectrl.o $(OBJDIR_DEBUG)/src/json.o $(OBJDIR_DEBUG)/IHM/EvtMainFrame.o $(OBJDIR_DEBUG)/IHM/EvtBanCreateDialog.o $(OBJDIR_DEBUG)/IHM/EvtGroupPermissionsDialog.o $(OBJDIR_DEBUG)/IHM/EvtLicenceInfoDialog.o $(OBJDIR_DEBUG)/IHM/BanCreateDialog.o $(OBJDIR_DEBUG)/IHM/EvtUserModDialog.o $(OBJDIR_DEBUG)/IHM/GroupPermissionsDialog.o $(OBJDIR_DEBUG)/IHM/LicenceInfoDialog.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/MyApp.o $(OBJDIR_RELEASE)/IHM/MainFrame.o $(OBJDIR_RELEASE)/IHM/UserModDialog.o $(OBJDIR_RELEASE)/src/RESTClient.o $(OBJDIR_RELEASE)/src/checktreectrl.o $(OBJDIR_RELEASE)/src/json.o $(OBJDIR_RELEASE)/IHM/EvtMainFrame.o $(OBJDIR_RELEASE)/IHM/EvtBanCreateDialog.o $(OBJDIR_RELEASE)/IHM/EvtGroupPermissionsDialog.o $(OBJDIR_RELEASE)/IHM/EvtLicenceInfoDialog.o $(OBJDIR_RELEASE)/IHM/BanCreateDialog.o $(OBJDIR_RELEASE)/IHM/EvtUserModDialog.o $(OBJDIR_RELEASE)/IHM/GroupPermissionsDialog.o $(OBJDIR_RELEASE)/IHM/LicenceInfoDialog.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/IHM || mkdir -p $(OBJDIR_DEBUG)/IHM
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/MyApp.o: MyApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MyApp.cpp -o $(OBJDIR_DEBUG)/MyApp.o

$(OBJDIR_DEBUG)/IHM/MainFrame.o: IHM/MainFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/MainFrame.cpp -o $(OBJDIR_DEBUG)/IHM/MainFrame.o

$(OBJDIR_DEBUG)/IHM/UserModDialog.o: IHM/UserModDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/UserModDialog.cpp -o $(OBJDIR_DEBUG)/IHM/UserModDialog.o

$(OBJDIR_DEBUG)/src/RESTClient.o: src/RESTClient.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/RESTClient.cpp -o $(OBJDIR_DEBUG)/src/RESTClient.o

$(OBJDIR_DEBUG)/src/checktreectrl.o: src/checktreectrl.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/checktreectrl.cpp -o $(OBJDIR_DEBUG)/src/checktreectrl.o

$(OBJDIR_DEBUG)/src/json.o: src/json.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/json.cpp -o $(OBJDIR_DEBUG)/src/json.o

$(OBJDIR_DEBUG)/IHM/EvtMainFrame.o: IHM/EvtMainFrame.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/EvtMainFrame.cpp -o $(OBJDIR_DEBUG)/IHM/EvtMainFrame.o

$(OBJDIR_DEBUG)/IHM/EvtBanCreateDialog.o: IHM/EvtBanCreateDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/EvtBanCreateDialog.cpp -o $(OBJDIR_DEBUG)/IHM/EvtBanCreateDialog.o

$(OBJDIR_DEBUG)/IHM/EvtGroupPermissionsDialog.o: IHM/EvtGroupPermissionsDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/EvtGroupPermissionsDialog.cpp -o $(OBJDIR_DEBUG)/IHM/EvtGroupPermissionsDialog.o

$(OBJDIR_DEBUG)/IHM/EvtLicenceInfoDialog.o: IHM/EvtLicenceInfoDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/EvtLicenceInfoDialog.cpp -o $(OBJDIR_DEBUG)/IHM/EvtLicenceInfoDialog.o

$(OBJDIR_DEBUG)/IHM/BanCreateDialog.o: IHM/BanCreateDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/BanCreateDialog.cpp -o $(OBJDIR_DEBUG)/IHM/BanCreateDialog.o

$(OBJDIR_DEBUG)/IHM/EvtUserModDialog.o: IHM/EvtUserModDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/EvtUserModDialog.cpp -o $(OBJDIR_DEBUG)/IHM/EvtUserModDialog.o

$(OBJDIR_DEBUG)/IHM/GroupPermissionsDialog.o: IHM/GroupPermissionsDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/GroupPermissionsDialog.cpp -o $(OBJDIR_DEBUG)/IHM/GroupPermissionsDialog.o

$(OBJDIR_DEBUG)/IHM/LicenceInfoDialog.o: IHM/LicenceInfoDialog.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c IHM/LicenceInfoDialog.cpp -o $(OBJDIR_DEBUG)/IHM/LicenceInfoDialog.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/IHM || mkdir -p $(OBJDIR_RELEASE)/IHM
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/MyApp.o: MyApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MyApp.cpp -o $(OBJDIR_RELEASE)/MyApp.o

$(OBJDIR_RELEASE)/IHM/MainFrame.o: IHM/MainFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/MainFrame.cpp -o $(OBJDIR_RELEASE)/IHM/MainFrame.o

$(OBJDIR_RELEASE)/IHM/UserModDialog.o: IHM/UserModDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/UserModDialog.cpp -o $(OBJDIR_RELEASE)/IHM/UserModDialog.o

$(OBJDIR_RELEASE)/src/RESTClient.o: src/RESTClient.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RESTClient.cpp -o $(OBJDIR_RELEASE)/src/RESTClient.o

$(OBJDIR_RELEASE)/src/checktreectrl.o: src/checktreectrl.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/checktreectrl.cpp -o $(OBJDIR_RELEASE)/src/checktreectrl.o

$(OBJDIR_RELEASE)/src/json.o: src/json.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/json.cpp -o $(OBJDIR_RELEASE)/src/json.o

$(OBJDIR_RELEASE)/IHM/EvtMainFrame.o: IHM/EvtMainFrame.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/EvtMainFrame.cpp -o $(OBJDIR_RELEASE)/IHM/EvtMainFrame.o

$(OBJDIR_RELEASE)/IHM/EvtBanCreateDialog.o: IHM/EvtBanCreateDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/EvtBanCreateDialog.cpp -o $(OBJDIR_RELEASE)/IHM/EvtBanCreateDialog.o

$(OBJDIR_RELEASE)/IHM/EvtGroupPermissionsDialog.o: IHM/EvtGroupPermissionsDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/EvtGroupPermissionsDialog.cpp -o $(OBJDIR_RELEASE)/IHM/EvtGroupPermissionsDialog.o

$(OBJDIR_RELEASE)/IHM/EvtLicenceInfoDialog.o: IHM/EvtLicenceInfoDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/EvtLicenceInfoDialog.cpp -o $(OBJDIR_RELEASE)/IHM/EvtLicenceInfoDialog.o

$(OBJDIR_RELEASE)/IHM/BanCreateDialog.o: IHM/BanCreateDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/BanCreateDialog.cpp -o $(OBJDIR_RELEASE)/IHM/BanCreateDialog.o

$(OBJDIR_RELEASE)/IHM/EvtUserModDialog.o: IHM/EvtUserModDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/EvtUserModDialog.cpp -o $(OBJDIR_RELEASE)/IHM/EvtUserModDialog.o

$(OBJDIR_RELEASE)/IHM/GroupPermissionsDialog.o: IHM/GroupPermissionsDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/GroupPermissionsDialog.cpp -o $(OBJDIR_RELEASE)/IHM/GroupPermissionsDialog.o

$(OBJDIR_RELEASE)/IHM/LicenceInfoDialog.o: IHM/LicenceInfoDialog.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c IHM/LicenceInfoDialog.cpp -o $(OBJDIR_RELEASE)/IHM/LicenceInfoDialog.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

