///////////////////////////////////////////////////////////////////////////
//
//    wxRemoteTShockManager
//    Copyright (C) 2017  Guillaume Jacquemin ("William JCM", "williamjcm")
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////

#ifndef __EvtMainFrame__
#define __EvtMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "MainFrame.h"

//// end generated include

#include <wx/msgdlg.h>
#include <wx/log.h>
#include <wx/tokenzr.h>
#include <wx/arrstr.h>
#include <wx/textdlg.h>
#include <wx/colordlg.h>
#include <wx/regex.h>
#include "res/tshock.xpm"
#include "../include/json.h"
#include "../include/RESTClient.h"
#include "EvtUserModDialog.h"
#include "EvtBanCreateDialog.h"
#include "EvtLicenceInfoDialog.h"
#include "EvtGroupPermissionsDialog.h"
#include <wx/fileconf.h>

using namespace json;

/** Implementing MainFrame */
class EvtMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void OnManagerPageChanged( wxNotebookEvent& event );
		void OnButtonConnectClick( wxCommandEvent& event );
		void OnButtonStatusClick( wxCommandEvent& event );
		void OnButtonMotDClick( wxCommandEvent& event );
		void OnButtonRulesClick( wxCommandEvent& event );
		void OnButtonReloadConfigClick( wxCommandEvent& event );
		void OnButtonRestartClick( wxCommandEvent& event );
		void OnButtonShutdownClick( wxCommandEvent& event );
		void OnButtonBroadcastClick( wxCommandEvent& event );
		void OnButtonRawCmdClick( wxCommandEvent& event );
		void OnButtonPlayerInfoClick( wxCommandEvent& event );
		void OnButtonKickPlayerClick( wxCommandEvent& event );
		void OnButtonBanPlayerClick( wxCommandEvent& event );
		void OnButtonKillPlayerClick( wxCommandEvent& event );
		void OnButtonMutePlayerClick( wxCommandEvent& event );
		void OnButtonUnmutePlayerClick( wxCommandEvent& event );
		void OnButtonMoreUserInfoClick( wxCommandEvent& event );
		void OnButtonCreateUserClick( wxCommandEvent& event );
		void OnButtonEditUserClick( wxCommandEvent& event );
		void OnButtonDeleteUserClick( wxCommandEvent& event );
		void OnButtonMoreGroupInfoClick( wxCommandEvent& event );
		void OnButtonGroupCreateClick( wxCommandEvent& event );
		void OnButtonGroupEditClick( wxCommandEvent& event );
		void OnButtonGroupDeleteClick( wxCommandEvent& event );
		void OnButtonMoreBanInfoClick( wxCommandEvent& event );
		void OnButtonCreateBanButtonClick( wxCommandEvent& event );
		void OnButtonDeleteBanClick( wxCommandEvent& event );
		void OnButtonReadWorldClick( wxCommandEvent& event );
		void OnButtonSaveWorldClick( wxCommandEvent& event );
		void OnButtonEnableWorldAutosaveButtonClick( wxCommandEvent& event );
		void OnButtonDisableWorldAutosaveClick( wxCommandEvent& event );
		void OnButtonMeteorFall( wxCommandEvent& event );
		void OnButtonStartBloodmoonClick( wxCommandEvent& event );
		void OnButtonStopBloodmoonClick( wxCommandEvent& event );
		void OnButtonButcherClick( wxCommandEvent& event );
		void OnButtonLicenceInfoClick( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtMainFrame( wxWindow* parent );
	//// end generated class members
        ~EvtMainFrame();
	private:
	    RESTClient m_TShockRESTClient;
	    void ShowError(wxString ErrorMessage);
	    void ShowInfo(wxString InfoMessage);
	    void SetTabs(bool Connected);
	    void RefreshPlayerList();
	    void RefreshUserList();
	    void RefreshGroupList();
	    void RefreshBanList();
	    EvtGroupPermissionsDialog *m_GroupPermissionsDialog;
	    wxFileConfig *m_LastServerConfig;
};

#endif // __EvtMainFrame__
