///////////////////////////////////////////////////////////////////////////
//
//    wxRemoteTShockManager
//    Copyright (C) 2017  Guillaume Jacquemin ("William JCM", "williamjcm")
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
///////////////////////////////////////////////////////////////////////////

#ifndef __EvtUserModDialog__
#define __EvtUserModDialog__

/**
@file
Subclass of UserModDialog, which is generated by wxFormBuilder.
*/

#include "UserModDialog.h"

//// end generated include

#include <wx/arrstr.h>
#include <wx/msgdlg.h>

/** Implementing UserModDialog */
class EvtUserModDialog : public UserModDialog
{
protected:
    // Handlers for UserModDialog events.
    void OnButtonCancelUserClick( wxCommandEvent& event );
    void OnButtonSaveUserClick( wxCommandEvent& event );
public:
    /** Constructor */
    EvtUserModDialog( wxWindow* parent );
    //// end generated class members
    EvtUserModDialog( wxWindow* parent, wxArrayString Groups );
    EvtUserModDialog( wxWindow* parent, wxString Username, wxArrayString Groups );
    wxArrayString GetFields();
private:
    void FillGroupChoice(wxArrayString Groups);
};

#endif // __EvtUserModDialog__
